swagger: '2.0'
info:
  description: Generate stats and metrics for mobile advertising campaigns.
  version: 1.0.1
  title: Reveal Mobile Attribution Report API
  # put the contact info for your development or API team
  contact:
    email: enginnering@revalmobile.com

  # license:
  #   name: Apache 2.0
  #   url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /report/project/{project_id}/visitor:
    get:
      tags:
        - developers
      summary: Visitor Count Report
      operationId: countVisitors
      description: |
        # Get a report of Visitors within a specified date range, to a specified project. 

        ### Optional Fiters 
        * **Repeat Visitors** - Visited Project locations more than 1x in report period.
        * **Target Visitors** - Visited project location that was situated within a specified proximity of the Visitor's recorded Home or Work location. 

        ### Output Formats
        * **Count** - returns a raw count of unique Visitors matching the specified criteria.
        * **Percentage** - returns a percentage metric indicating the ratio of project visitors within a specified proximity of their Home or Work location to total project Visitors within the report period.
        * **Index** - returns an index value comparison in unique Visitors
      produces:
        - application/json
      parameters:
        - in: path
          name: project_id
          description: The id of the advertiser
          type: integer
          format: int64
          required: true
        - in: query
          name: from
          description: The start date of the report.
          required: true
          type: string
          format: date
          pattern: "YYYY-MM-DD"
        - in: query
          name: to
          description: The end date of the report.
          required: true
          type: string
          format: date
          pattern: "YYYY-MM-DD"
        - in: query
          name: format
          required: true
          type: string
          enum: [Count, Index, Percentage]
          description: The metric format for the report
        - in: query
          name: repeat
          type: boolean
          default: false
          description: Flag to include only Visitors observed twice in the requested range. Only applies to metric formats *Count* and *Percentage*
        - in: query
          name: distance
          type: integer
          format: int32
          description: Includes visitors within the specified distance of a Visitor's Home or Work location.
        - in: query
          name: target
          type: string
          enum: [Home, Work]
      responses:
        200:
          description: A basic response including report data and response messages.
          schema:
            $ref: '#/definitions/BasicResponse'
        400:
          description: bad input parameter
definitions:
  BasicResponse:
    type: object
    required:
      - data
      - messages
    properties:
      data:
        description: Results of the report request.
        type: object
        example: {
          "Walmart": "112000",
          "Target": "95000"
        }
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
  Message:
    type: object
    required:
      - context
      - level
      - text
    properties:
      context:
        type: string
        example: "*"
      level:
        type: string
        example: success
      text:
        type: string
        example: Request Successful